pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "harsha6798/voting-app-vote-service-ci-image:${BUILD_NUMBER}"
    }

    stages{
        
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/harsha-ops/Voting-App.git'
            }
            
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ./vote/"
            }
        }

        stage('Login to Docker Registry') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker_cred', // Use your actual credentials ID
                    usernameVariable: 'DOCKER_USERNAME', 
                    passwordVariable: 'DOCKER_PASSWORD'
            )]) {
                sh '''
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                '''
            }

            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }

        stage('Update k8s maifest') {
            steps {
                
                sh '''
                export REPO_URL="https://${github_token}@github.com/harsha-ops/Simple-Voting-APP-ArgoCD.git"
                sh updatek8smanifest.sh vote-microservice ${DOCKER_IMAGE}
                '''
            }
        }



        


    }
}