pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "harsha6798/voting-app-worker-service-ci-image:${BUILD_NUMBER}"
    }

    stages{
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/harsha-ops/Voting-App.git'
            }
            
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ./worker/"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }

        stage('Update k8s maifest') {
            steps {
                
                sh '''
                export REPO_URL="https://${GITHUB_TOKEN}@github.com/harsha-ops/Simple-Voting-APP-ArgoCD.git"
                sh updatek8smanifest.sh worker-microservice ${DOCKER_IMAGE}
                '''
            }
        }

        


    }
}